# Generated by Django 5.0.1 on 2025-05-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_hidden_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
