# Generated by Django 5.0.1 on 2025-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated list of tags', null=True),
        ),
    ]
