# Generated by Django 4.2.6 on 2025-05-02 17:16

from django.db import migrations
import profiles.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_level_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', profiles.managers.CustomUserManager()),
            ],
        ),
    ]
