# Generated by Django 5.0.1 on 2025-05-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_max_capacity_event_required_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
