# Generated by Django 4.2.6 on 2025-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubscription',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
