# Generated by Django 5.0.1 on 2025-03-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
