# Generated by Django 5.0.1 on 2025-05-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated list of tags'),
        ),
    ]
